### PR TITLE
Print error output from CPython / Make sure we use python2

### PR DESCRIPTION
**Pull request by aaiyer**

### CODE REVIEW

**Comment by lopuhin** [comment]
Regarding PyErr_Clear -> PyErr_Print change, note that this was changed in the other direction here - https://github.com/rguillebert/pymetabiosis/commit/69302f4a16aeb23449ffe90aaa7e3b6cbeef7df6 - I think @rguillebert will be able to give precise reason, and then we can discuss what a better solution could be.

**Comment by rguillebert** [comment]
Printing the exception to standard output is not a good solution

**Comment by rguillebert** [comment]
We should propagate that error properly on the pypy side

**Comment by lopuhin** [comment]
Oh, sure, you are right! The exception could be caught.
Right now only the exception type is propagated, I think it should be relatively possible to propagate the value for some cases, and maybe even reconstruct the traceback?

**Comment by rguillebert** [comment]
I'd like to have the traceback somehow yes, I think some people do it over the network already

**Pull request closed without merging**
